# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuscarTodosUsuarios = channel.unary_unary(
                '/StreamingGrpc/BuscarTodosUsuarios',
                request_serializer=streaming__pb2.BuscarTodosUsuariosRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarTodosUsuariosResponse.FromString,
                _registered_method=True)
        self.BuscarUsuario = channel.unary_unary(
                '/StreamingGrpc/BuscarUsuario',
                request_serializer=streaming__pb2.BuscarUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarUsuarioResponse.FromString,
                _registered_method=True)
        self.BuscarTodasMusicas = channel.unary_unary(
                '/StreamingGrpc/BuscarTodasMusicas',
                request_serializer=streaming__pb2.BuscarTodasMusicasRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarTodasMusicasResponse.FromString,
                _registered_method=True)
        self.BuscarMusica = channel.unary_unary(
                '/StreamingGrpc/BuscarMusica',
                request_serializer=streaming__pb2.BuscarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarMusicaResponse.FromString,
                _registered_method=True)
        self.BuscarTodasPlaylists = channel.unary_unary(
                '/StreamingGrpc/BuscarTodasPlaylists',
                request_serializer=streaming__pb2.BuscarTodasPlaylistsRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarTodasPlaylistsResponse.FromString,
                _registered_method=True)
        self.BuscarPlaylist = channel.unary_unary(
                '/StreamingGrpc/BuscarPlaylist',
                request_serializer=streaming__pb2.BuscarPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarPlaylistResponse.FromString,
                _registered_method=True)
        self.BuscarPlaylistsPorUsuario = channel.unary_unary(
                '/StreamingGrpc/BuscarPlaylistsPorUsuario',
                request_serializer=streaming__pb2.BuscarPlaylistsPorUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarPlaylistsPorUsuarioResponse.FromString,
                _registered_method=True)
        self.BuscarMusicasPorPlaylist = channel.unary_unary(
                '/StreamingGrpc/BuscarMusicasPorPlaylist',
                request_serializer=streaming__pb2.BuscarMusicasPorPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarMusicasPorPlaylistResponse.FromString,
                _registered_method=True)
        self.BuscarPlaylistsPorMusica = channel.unary_unary(
                '/StreamingGrpc/BuscarPlaylistsPorMusica',
                request_serializer=streaming__pb2.BuscarPlaylistsPorMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.BuscarPlaylistsPorMusicaResponse.FromString,
                _registered_method=True)
        self.CriarUsuario = channel.unary_unary(
                '/StreamingGrpc/CriarUsuario',
                request_serializer=streaming__pb2.CriarUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.UsuarioGrpc.FromString,
                _registered_method=True)
        self.AtualizarUsuario = channel.unary_unary(
                '/StreamingGrpc/AtualizarUsuario',
                request_serializer=streaming__pb2.AtualizarUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.UsuarioGrpc.FromString,
                _registered_method=True)
        self.DeletarUsuario = channel.unary_unary(
                '/StreamingGrpc/DeletarUsuario',
                request_serializer=streaming__pb2.DeletarUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.DeletarResponse.FromString,
                _registered_method=True)
        self.CriarMusica = channel.unary_unary(
                '/StreamingGrpc/CriarMusica',
                request_serializer=streaming__pb2.CriarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.MusicaGrpc.FromString,
                _registered_method=True)
        self.AtualizarMusica = channel.unary_unary(
                '/StreamingGrpc/AtualizarMusica',
                request_serializer=streaming__pb2.AtualizarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.MusicaGrpc.FromString,
                _registered_method=True)
        self.DeletarMusica = channel.unary_unary(
                '/StreamingGrpc/DeletarMusica',
                request_serializer=streaming__pb2.DeletarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.DeletarResponse.FromString,
                _registered_method=True)
        self.CriarPlaylist = channel.unary_unary(
                '/StreamingGrpc/CriarPlaylist',
                request_serializer=streaming__pb2.CriarPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.PlaylistGrpc.FromString,
                _registered_method=True)
        self.AtualizarPlaylist = channel.unary_unary(
                '/StreamingGrpc/AtualizarPlaylist',
                request_serializer=streaming__pb2.AtualizarPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.PlaylistGrpc.FromString,
                _registered_method=True)
        self.DeletarPlaylist = channel.unary_unary(
                '/StreamingGrpc/DeletarPlaylist',
                request_serializer=streaming__pb2.DeletarPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.DeletarResponse.FromString,
                _registered_method=True)


class StreamingGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuscarTodosUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarTodasMusicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarTodasPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarPlaylistsPorUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarMusicasPorPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarPlaylistsPorMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarUsuario(self, request, context):
        """CRUD Usuarios
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarMusica(self, request, context):
        """CRUD Musicas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarPlaylist(self, request, context):
        """CRUD Playlists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuscarTodosUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarTodosUsuarios,
                    request_deserializer=streaming__pb2.BuscarTodosUsuariosRequest.FromString,
                    response_serializer=streaming__pb2.BuscarTodosUsuariosResponse.SerializeToString,
            ),
            'BuscarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarUsuario,
                    request_deserializer=streaming__pb2.BuscarUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.BuscarUsuarioResponse.SerializeToString,
            ),
            'BuscarTodasMusicas': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarTodasMusicas,
                    request_deserializer=streaming__pb2.BuscarTodasMusicasRequest.FromString,
                    response_serializer=streaming__pb2.BuscarTodasMusicasResponse.SerializeToString,
            ),
            'BuscarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarMusica,
                    request_deserializer=streaming__pb2.BuscarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.BuscarMusicaResponse.SerializeToString,
            ),
            'BuscarTodasPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarTodasPlaylists,
                    request_deserializer=streaming__pb2.BuscarTodasPlaylistsRequest.FromString,
                    response_serializer=streaming__pb2.BuscarTodasPlaylistsResponse.SerializeToString,
            ),
            'BuscarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarPlaylist,
                    request_deserializer=streaming__pb2.BuscarPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.BuscarPlaylistResponse.SerializeToString,
            ),
            'BuscarPlaylistsPorUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarPlaylistsPorUsuario,
                    request_deserializer=streaming__pb2.BuscarPlaylistsPorUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.BuscarPlaylistsPorUsuarioResponse.SerializeToString,
            ),
            'BuscarMusicasPorPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarMusicasPorPlaylist,
                    request_deserializer=streaming__pb2.BuscarMusicasPorPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.BuscarMusicasPorPlaylistResponse.SerializeToString,
            ),
            'BuscarPlaylistsPorMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarPlaylistsPorMusica,
                    request_deserializer=streaming__pb2.BuscarPlaylistsPorMusicaRequest.FromString,
                    response_serializer=streaming__pb2.BuscarPlaylistsPorMusicaResponse.SerializeToString,
            ),
            'CriarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarUsuario,
                    request_deserializer=streaming__pb2.CriarUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.UsuarioGrpc.SerializeToString,
            ),
            'AtualizarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarUsuario,
                    request_deserializer=streaming__pb2.AtualizarUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.UsuarioGrpc.SerializeToString,
            ),
            'DeletarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletarUsuario,
                    request_deserializer=streaming__pb2.DeletarUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.DeletarResponse.SerializeToString,
            ),
            'CriarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarMusica,
                    request_deserializer=streaming__pb2.CriarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.MusicaGrpc.SerializeToString,
            ),
            'AtualizarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarMusica,
                    request_deserializer=streaming__pb2.AtualizarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.MusicaGrpc.SerializeToString,
            ),
            'DeletarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletarMusica,
                    request_deserializer=streaming__pb2.DeletarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.DeletarResponse.SerializeToString,
            ),
            'CriarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPlaylist,
                    request_deserializer=streaming__pb2.CriarPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.PlaylistGrpc.SerializeToString,
            ),
            'AtualizarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarPlaylist,
                    request_deserializer=streaming__pb2.AtualizarPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.PlaylistGrpc.SerializeToString,
            ),
            'DeletarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletarPlaylist,
                    request_deserializer=streaming__pb2.DeletarPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.DeletarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StreamingGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('StreamingGrpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuscarTodosUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarTodosUsuarios',
            streaming__pb2.BuscarTodosUsuariosRequest.SerializeToString,
            streaming__pb2.BuscarTodosUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarUsuario',
            streaming__pb2.BuscarUsuarioRequest.SerializeToString,
            streaming__pb2.BuscarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarTodasMusicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarTodasMusicas',
            streaming__pb2.BuscarTodasMusicasRequest.SerializeToString,
            streaming__pb2.BuscarTodasMusicasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarMusica',
            streaming__pb2.BuscarMusicaRequest.SerializeToString,
            streaming__pb2.BuscarMusicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarTodasPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarTodasPlaylists',
            streaming__pb2.BuscarTodasPlaylistsRequest.SerializeToString,
            streaming__pb2.BuscarTodasPlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarPlaylist',
            streaming__pb2.BuscarPlaylistRequest.SerializeToString,
            streaming__pb2.BuscarPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarPlaylistsPorUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarPlaylistsPorUsuario',
            streaming__pb2.BuscarPlaylistsPorUsuarioRequest.SerializeToString,
            streaming__pb2.BuscarPlaylistsPorUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarMusicasPorPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarMusicasPorPlaylist',
            streaming__pb2.BuscarMusicasPorPlaylistRequest.SerializeToString,
            streaming__pb2.BuscarMusicasPorPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarPlaylistsPorMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/BuscarPlaylistsPorMusica',
            streaming__pb2.BuscarPlaylistsPorMusicaRequest.SerializeToString,
            streaming__pb2.BuscarPlaylistsPorMusicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/CriarUsuario',
            streaming__pb2.CriarUsuarioRequest.SerializeToString,
            streaming__pb2.UsuarioGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/AtualizarUsuario',
            streaming__pb2.AtualizarUsuarioRequest.SerializeToString,
            streaming__pb2.UsuarioGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/DeletarUsuario',
            streaming__pb2.DeletarUsuarioRequest.SerializeToString,
            streaming__pb2.DeletarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/CriarMusica',
            streaming__pb2.CriarMusicaRequest.SerializeToString,
            streaming__pb2.MusicaGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/AtualizarMusica',
            streaming__pb2.AtualizarMusicaRequest.SerializeToString,
            streaming__pb2.MusicaGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/DeletarMusica',
            streaming__pb2.DeletarMusicaRequest.SerializeToString,
            streaming__pb2.DeletarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/CriarPlaylist',
            streaming__pb2.CriarPlaylistRequest.SerializeToString,
            streaming__pb2.PlaylistGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/AtualizarPlaylist',
            streaming__pb2.AtualizarPlaylistRequest.SerializeToString,
            streaming__pb2.PlaylistGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/StreamingGrpc/DeletarPlaylist',
            streaming__pb2.DeletarPlaylistRequest.SerializeToString,
            streaming__pb2.DeletarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
